server:
  port: 8081

orm:
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bobasyu?useUnicode=true
    username: bobasyu
    password: zhoubo
    mapper-locations: classpath*:mapper/*.xml
    base-mapper-package: cn.bobasyu.orm.test.mapper
